name: Publish to Pypi

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - './tests/**'
      - './.github/workflows/test.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Publish lib
        shell: bash
        run: |
          pip install "poetry==${{ vars.POETRY_VERSION }}"
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build

      - name: Automatic release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'v1.2.2 New methods in LdapService'
          prerelease: false
          automatic_release_tag: v1.2.2
          files: |
            LICENSE
